[programs.devnet]
backend = "4NFLW2PAgeWw7iC5Q2ZawZYSbGHwMEzicP2oYsqVkxTy"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/esben/.config/solana/id.json"

[scripts]
test = "node tests/backend.js"
